name: CI

on:
    push:
    pull_request:

env:
  APP_DEV: ${{ secrets.APP_DEV }}
  PROJECT_HOST: ${{ secrets.PROJECT_HOST }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  SERVER_NAME: ${{ secrets.SERVER_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PWD: ${{ secrets.DB_PWD }}

jobs:
    tests:
        name: Docker build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Pull images
              run: docker-compose pull
            - name: Start services
              run: docker-compose up --build -d
            - name: Sleep for 5 seconds
              uses: jakejarvis/wait-action@master
              with:
                time: '5s'
            - name: Check HTTP reachability
              run: curl -v -o /dev/null $SERVER_NAME
            - name: Check HTTPS reachability
              run: curl  -vk -o /dev/null $SERVER_NAME
            - name: PHPUnit
              run: docker-compose exec -T php bin/phpunit
