name: CI

on:
    push:
    pull_request:

env:
  APP_DEV: ${{ secrets.APP_DEV }}
  PROJECT_HOST: ${{ secrets.PROJECT_HOST }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  SERVER_NAME: ${{ secrets.SERVER_NAME }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PWD: ${{ secrets.DB_PWD }}

jobs:
    tests:
        name: Docker build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Pull images
              run: docker-compose pull
            - name: Start services
              run: docker-compose up --build -d
              env:
                APP_ENV: "$APP_ENV"
                DATABASE_URL: "postgres://$DB_USER:$DB_PWD@app-db:5432/app?sslmode=disable&charset=utf8"
                PHP_EXTENSION_PGSQL: 1
                PHP_EXTENSION_PDOPGSQL: 1
                PHP_EXTENSION_INTL: 1
                PHP_EXTENSION_GD: 1
                PHP_INI_MEMORY_LIMIT: -1
                # PHP_EXTENSION_XDEBUG: 1
                # PHP_INI_XDEBUG__REMOTE_AUTOSTART: 1

                STARTUP_COMMAND_1: composer install
                STARTUP_COMMAND_2: echo 'alias sf="php bin/console"' >> ~/.bashrc
                STARTUP_COMMAND_3: echo 'alias phpunit="php vendor/bin/simple-phpunit"' >> ~/.bashrc
            - name: Run composer
              run: docker exec -t app-php composer install
            - name: Sleep for 5 seconds
              uses: jakejarvis/wait-action@master
              with:
                time: '5s'
            - name: Check HTTP reachability
              run: curl -v -o /dev/null http://$PROJECT_HOST
            # - name: Check HTTPS reachability
            #   run: curl  -vk -o /dev/null https://$PROJECT_HOST
            - name: PHPUnit
              run: docker exec -t app-php php /srv/api/vendor/bin/simple-phpunit
